/**
 * Reviewed standalone meanings for German words that are genuinely
 * polysemous across Micheon's contextual packs.
 *
 * A lesson about academic writing may correctly teach `belegen` as “to
 * substantiate”, while a course pack may use it for taking a course. Neither
 * contextual meaning should win the global word card merely because its pack
 * was loaded first. These entries are deliberately authored, not generated:
 * they give Word mode, Listen, the tracker and Micheon Immersion one useful
 * everyday-first card while the original packs keep their precise meanings.
 */
type CanonicalWordSense = {
  de: string;
  en: string;
  use: string;
  level?: string;
  pos?: string;
};

const REVIEWED_WORD_SENSES: Record<string, CanonicalWordSense> = {
  bus: {
    de: "der Bus",
    en: "bus or coach",
    use: "Everyday meaning: der Bus = bus. In a Fortnite context, the same word can refer to the Battle Bus, but that game-specific meaning is not part of this answer.",
    level: "A1",
    pos: "noun",
  },
  literatur: {
    de: "die Literatur",
    en: "literature",
    use: "Everyday meaning: books and written works. In university or research contexts, wissenschaftliche Literatur means academic literature.",
    level: "A2",
    pos: "noun",
  },
  milliarde: {
    de: "die Milliarde",
    en: "billion",
    use: "Scale bridge: German Million = English million = 1,000,000; German Milliarde = English billion = 1,000,000,000; German Billion = English trillion = 1,000,000,000,000. Translate English billion as Milliarde, never Billion.",
    level: "A2",
    pos: "noun",
  },
  gericht: {
    de: "das Gericht",
    en: "court",
    use: "This card teaches the legal sense: vor Gericht = in court. In a food context, das Gericht means a dish or meal; that is a separate meaning and is not part of this answer.",
    level: "B1",
    pos: "noun",
  },
  leistung: {
    de: "die Leistung",
    en: "performance or achievement",
    use: "In insurance and public services, Leistung can also mean a benefit or provided service.",
    level: "A2",
    pos: "noun",
  },
  folge: {
    de: "die Folge",
    en: "result or consequence",
    use: "For a television or podcast series, Folge means an episode.",
    level: "A2",
    pos: "noun",
  },
  punkt: {
    de: "der Punkt",
    en: "point",
    use: "Depending on context, Punkt also means a dot, a full stop, or a score point.",
    level: "A1",
    pos: "noun",
  },
  antrag: {
    de: "der Antrag",
    en: "application or formal request",
    use: "In a meeting or parliament, Antrag can also mean a proposal or motion.",
    level: "A2",
    pos: "noun",
  },
  anlage: {
    de: "die Anlage",
    en: "facility or system",
    use: "Anlage can also mean an attachment, an investment, or a stereo system.",
    level: "B1",
    pos: "noun",
  },
  stand: {
    de: "der Stand",
    en: "state or status",
    use: "Stand can also mean a stand, stall, or position, depending on the situation.",
    level: "A2",
    pos: "noun",
  },
  abschließen: {
    de: "abschließen",
    en: "to finish or complete",
    use: "It can also mean to lock something or to take out a contract or insurance policy.",
    level: "A2",
    pos: "verb",
  },
  ankommen: {
    de: "ankommen",
    en: "to arrive",
    use: "Auf etwas ankommen means that something depends on or comes down to that thing.",
    level: "A1",
    pos: "verb",
  },
  reichen: {
    de: "reichen",
    en: "to be enough",
    use: "With an object, reichen can also mean to pass or hand something to someone.",
    level: "A2",
    pos: "verb",
  },
  anmeldung: {
    de: "die Anmeldung",
    en: "registration or sign-up",
    use: "At a hotel, clinic, or office, Anmeldung can also refer to check-in or reception.",
    level: "A2",
    pos: "noun",
  },
  mitteilung: {
    de: "die Mitteilung",
    en: "notification",
    use: "What X and most apps call their notifications tab: die Mitteilungen. Also a notice or formal communication — the everyday word for a message you send someone is die Nachricht.",
    level: "A2",
    pos: "noun",
  },
  meldung: {
    de: "die Meldung",
    en: "report",
    use: "A news bulletin, an official report, or a system message: die Fehlermeldung = error message. Reporting a post uses the verb melden.",
    level: "B1",
    pos: "noun",
  },
  verlauf: {
    de: "der Verlauf",
    en: "history or course",
    use: "In a browser or app, der Verlauf is your history. Elsewhere it is how something unfolded: im Verlauf des Abends = over the course of the evening.",
    level: "B1",
    pos: "noun",
  },
  erinnern: {
    de: "sich erinnern",
    en: "to remember",
    use: "Jemanden an etwas erinnern means to remind someone of something.",
    level: "A2",
    pos: "verb",
  },
  belegen: {
    de: "einen Kurs belegen",
    en: "to take a course",
    use: "Belegen also means to occupy or reserve something, support a claim with evidence, or top bread with something.",
    level: "B1",
    pos: "verb",
  },
  ansatz: {
    de: "der Ansatz",
    en: "approach or starting point",
    use: "For hair, Ansatz means the roots; in other contexts it can mean a base or beginning.",
    level: "B1",
    pos: "noun",
  },
  melden: {
    de: "sich melden",
    en: "to get in touch or speak up",
    use: "Without sich, melden can mean to report or register someone or something.",
    level: "A2",
    pos: "verb",
  },
  beschwerde: {
    de: "die Beschwerde",
    en: "complaint",
    use: "The plural Beschwerden can also mean symptoms or physical discomfort.",
    level: "B1",
    pos: "noun",
  },
  beschwerden: {
    de: "die Beschwerden",
    en: "symptoms or physical discomfort",
    use: "Beschwerden can also be the plural of Beschwerde: complaints.",
    level: "B1",
    pos: "noun",
  },
  stimmen: {
    de: "stimmen",
    en: "to be correct",
    use: "Stimmen can also mean to vote or to tune an instrument.",
    level: "A2",
    pos: "verb",
  },
  stimme: {
    de: "die Stimme",
    en: "voice",
    use: "Also a vote in an election, and a vocal part in music: die zweite Stimme = the second voice or part.",
    level: "A2",
    pos: "noun",
  },
  nachricht: {
    de: "die Nachricht",
    en: "message or news",
    use: "A message from someone or a news item; the surrounding context makes the meaning clear.",
    level: "A1",
    pos: "noun",
  },
  passen: {
    de: "passen",
    en: "to fit or suit",
    use: "For size, Das passt mir = it fits me; it can also mean something suits you or works for you. Appearance uses stehen.",
    level: "A2",
    pos: "verb",
  },
  hammer: {
    de: "der Hammer",
    en: "hammer, mallet",
    use: "Colloquially, Der Hammer! means amazing or awesome — the literal tool is the primary card meaning.",
    level: "A2",
    pos: "noun",
  },
  see: {
    de: "der See",
    en: "lake",
    use: "der See is a lake; die See is the sea. An den See fahren means to go to the lake.",
    level: "A2",
    pos: "noun",
  },
  ausleihen: {
    de: "ausleihen",
    en: "to borrow or lend",
    use: "sich etwas ausleihen = to borrow something; jemandem etwas ausleihen = to lend it to someone. In a shop it can also mean to hire or rent.",
    level: "A2",
    pos: "verb",
  },
  vornehmen: {
    de: "sich etwas vornehmen",
    en: "to plan to do something",
    use: "Also to resolve or intend to do something: Ich nehme mir vor, früher anzufangen = I plan to start earlier.",
    level: "B2",
    pos: "verb",
  },
  rezept: {
    de: "das Rezept",
    en: "recipe or prescription",
    use: "The surrounding conversation tells you whether it is for cooking or medicine.",
    level: "A2",
    pos: "noun",
  },
  zunehmen: {
    de: "zunehmen",
    en: "to increase or gain weight",
    use: "The general meaning is to increase; with a person it usually means to gain weight.",
    level: "A2",
    pos: "verb",
  },
  gang: {
    de: "der Gang",
    en: "corridor or aisle",
    use: "Gang can also mean a gear, a course of a meal, or someone's way of walking.",
    level: "A2",
    pos: "noun",
  },
  verlegen: {
    de: "verlegen",
    en: "to misplace or reschedule",
    use: "It can also mean to lay something or publish a book; the adjective verlegen means embarrassed.",
    level: "B1",
    pos: "verb",
  },
  widerspruch: {
    de: "der Widerspruch",
    en: "contradiction or objection",
    use: "In official correspondence, Widerspruch can mean a formal appeal.",
    level: "B1",
    pos: "noun",
  },
  überweisung: {
    de: "die Überweisung",
    en: "bank transfer or medical referral",
    use: "Both meanings are common; the situation makes the intended one clear.",
    level: "A2",
    pos: "noun",
  },
  beitrag: {
    de: "der Beitrag",
    en: "contribution or post",
    use: "On social media, ein Beitrag is a post. Elsewhere a contribution, a membership fee, or a broadcast article.",
    level: "B1",
    pos: "noun",
  },
  vorstellung: {
    de: "die Vorstellung",
    en: "idea or mental image",
    use: "It can also mean an introduction, a performance, or a cinema showing.",
    level: "B1",
    pos: "noun",
  },
  bewertung: {
    de: "die Bewertung",
    en: "rating or evaluation",
    use: "Use the context to tell whether it is a review score, assessment, or valuation.",
    level: "B1",
    pos: "noun",
  },
  station: {
    de: "die Station",
    en: "station or stop",
    use: "In a hospital, Station means a ward.",
    level: "A2",
    pos: "noun",
  },
  anschluss: {
    de: "der Anschluss",
    en: "connection or port",
    use: "It can be a transport connection, a socket or port, or a social connection.",
    level: "A2",
    pos: "noun",
  },
  absage: {
    de: "die Absage",
    en: "cancellation or rejection",
    use: "The same word is used when an event is cancelled or an application is rejected.",
    level: "B1",
    pos: "noun",
  },
  sicherung: {
    de: "die Sicherung",
    en: "fuse or backup",
    use: "More generally, Sicherung can mean protection or a safeguard.",
    level: "B1",
    pos: "noun",
  },
  übergang: {
    de: "der Übergang",
    en: "transition or crossing",
    use: "In audio, video, or hair styling, Übergang can also mean a fade.",
    level: "B1",
    pos: "noun",
  },
  verarbeiten: {
    de: "verarbeiten",
    en: "to process",
    use: "For a difficult experience, etwas verarbeiten means to cope with or come to terms with it.",
    level: "B1",
    pos: "verb",
  },
  bescheid: {
    de: "der Bescheid",
    en: "official notice or decision",
    use: "Bescheid sagen means to let someone know; Bescheid wissen means to know the situation.",
    level: "B1",
    pos: "noun",
  },
  lernen: {
    de: "lernen",
    en: "to learn",
    use: "Also to study for something: für eine Prüfung lernen. Studying a subject at university is studieren.",
    pos: "verb",
  },
  schaffen: {
    de: "schaffen",
    en: "to manage or get done",
    use: "Ich hab's geschafft = I did it, I made it. With strong forms (schuf, geschaffen) it means to create.",
    pos: "verb",
  },
  übernehmen: {
    de: "übernehmen",
    en: "to take over or take on",
    use: "Covers duties, costs and shifts alike: die Kosten übernehmen = to cover the costs.",
    pos: "verb",
  },
  einladen: {
    de: "einladen",
    en: "to invite",
    use: "Also to treat: Ich lade dich ein = it's on me. Loading cargo (Gepäck einladen) is the literal sense.",
    pos: "verb",
  },
  wahl: {
    de: "die Wahl",
    en: "choice",
    use: "Also the election: zur Wahl gehen = to go and vote. Keine Wahl haben = to have no choice.",
    pos: "noun",
  },
  auswahl: {
    de: "die Auswahl",
    en: "selection or range",
    use: "Eine große Auswahl = a wide range to choose from.",
    pos: "noun",
  },
  regional: {
    de: "regional",
    en: "regional or local",
    use: "Regionale Produkte are local produce — the everyday supermarket word.",
    pos: "adjective",
  },
  fordern: {
    de: "fordern",
    en: "to demand",
    use: "Also to challenge someone: der Job fordert mich. Asking politely is bitten, not fordern.",
    pos: "verb",
  },
  überzeugen: {
    de: "überzeugen",
    en: "to convince",
    use: "überzeugt sein = to be sure of something. Talking someone into an action is überreden.",
    pos: "verb",
  },
  zusammenhang: {
    de: "der Zusammenhang",
    en: "connection or context",
    use: "Im Zusammenhang mit = in connection with; kein Zusammenhang = no link.",
    pos: "noun",
  },
  änderung: {
    de: "die Änderung",
    en: "change",
    use: "A tailor's alteration is also eine Änderung; letzte Änderungen = last-minute changes.",
    pos: "noun",
  },
  feststellen: {
    de: "feststellen",
    en: "to notice or establish",
    use: "Ich habe festgestellt, dass ... = I noticed that ... Officially it means to determine a fact.",
    pos: "verb",
  },
  anpassen: {
    de: "anpassen",
    en: "to adjust",
    use: "sich anpassen = to adapt to something; Einstellungen anpassen = to tweak settings.",
    pos: "verb",
  },
  bund: {
    de: "das Bund",
    en: "bunch",
    use: "Ein Bund Radieschen = a bunch of radishes. DER Bund is the federation — im Bund = at federal level — and a waistband.",
    pos: "noun",
  },
  glauben: {
    de: "glauben",
    en: "to believe or think",
    use: "Ich glaube schon = I think so. glauben an + accusative = to believe in something.",
    pos: "verb",
  },
  auswirkung: {
    de: "die Auswirkung",
    en: "effect or impact",
    use: "Usually plural: die Auswirkungen auf = the effects on.",
    pos: "noun",
  },
  rund: {
    de: "rund",
    en: "round in shape",
    use: "Before a number it means roughly: rund 50 Euro = about 50 euros.",
    pos: "adjective",
  },
  kümmern: {
    de: "sich kümmern",
    en: "to take care of",
    use: "sich kümmern um + accusative: Ich kümmere mich drum = I'll handle it.",
    pos: "verb",
  },
  ermitteln: {
    de: "ermitteln",
    en: "to find out or determine",
    use: "The police sense is to investigate: die Polizei ermittelt.",
    pos: "verb",
  },
  verzichten: {
    de: "verzichten",
    en: "to do without",
    use: "verzichten auf + accusative: auf Zucker verzichten = to give up sugar.",
    pos: "verb",
  },
  abgeben: {
    de: "abgeben",
    en: "to hand in",
    use: "Also to give some away (Kannst du was abgeben?) and to cast a vote: seine Stimme abgeben.",
    pos: "verb",
  },
  gymnasium: {
    de: "das Gymnasium",
    en: "grammar school",
    use: "The academic secondary school leading to Abitur — not a gym, which is das Fitnessstudio.",
    pos: "noun",
  },
  vorschlag: {
    de: "der Vorschlag",
    en: "suggestion or proposal",
    use: "Ein Vorschlag zur Güte = a peace offer; Vorschläge machen = to make suggestions.",
    pos: "noun",
  },
  runde: {
    de: "die Runde",
    en: "round",
    use: "A game round, a lap, or a round of drinks: eine Runde geben = to buy a round. Über die Runden kommen = to get by.",
    pos: "noun",
  },
  rechnung: {
    de: "die Rechnung",
    en: "bill or invoice",
    use: "Die Rechnung, bitte! at the restaurant; an invoice from a company is also eine Rechnung.",
    pos: "noun",
  },
  umfang: {
    de: "der Umfang",
    en: "extent or scope",
    use: "In geometry it is the circumference; in vollem Umfang = in full.",
    pos: "noun",
  },
  anfangen: {
    de: "anfangen",
    en: "to start",
    use: "Fang einfach an = just get started. Nichts damit anfangen können = to have no use for it.",
    pos: "verb",
  },
  einreichen: {
    de: "einreichen",
    en: "to submit",
    use: "Formal hand-ins: einen Antrag einreichen = to file an application.",
    pos: "verb",
  },
  erinnerung: {
    de: "die Erinnerung",
    en: "memory",
    use: "Also a reminder: eine Erinnerung stellen = to set a reminder. Zur Erinnerung = as a keepsake.",
    pos: "noun",
  },
  übung: {
    de: "die Übung",
    en: "exercise or practice",
    use: "Übung macht den Meister = practice makes perfect.",
    pos: "noun",
  },
  kritik: {
    de: "die Kritik",
    en: "criticism",
    use: "A review is also eine Kritik; Kritik üben an = to criticise.",
    pos: "noun",
  },
  abstimmen: {
    de: "abstimmen",
    en: "to vote",
    use: "sich abstimmen = to coordinate with someone: Wir stimmen uns ab = we'll sync up.",
    pos: "verb",
  },
  nachweis: {
    de: "der Nachweis",
    en: "proof or evidence",
    use: "The document that proves something: ein Nachweis über die Impfung.",
    pos: "noun",
  },
  erledigen: {
    de: "erledigen",
    en: "to get done",
    use: "Ich erledige das = I'll sort it out. erledigt sein = to be worn out.",
    pos: "verb",
  },
  überlegen: {
    de: "überlegen",
    en: "to think it over",
    use: "Ich überlege es mir = I'll think about it. As an adjective, überlegen means superior.",
    pos: "verb",
  },
  profil: {
    de: "das Profil",
    en: "profile",
    use: "Your account profile online; on a tyre it is the tread — kaum noch Profil = hardly any tread left.",
    pos: "noun",
  },
  ablehnen: {
    de: "ablehnen",
    en: "to decline or reject",
    use: "Ein Angebot ablehnen = to turn an offer down; eine Anfrage ablehnen = to refuse it.",
    pos: "verb",
  },
  note: {
    de: "die Note",
    en: "grade or mark",
    use: "School grades, 1 is best. A musical note is also die Note; a written note is der Zettel or die Notiz.",
    pos: "noun",
  },
  kurzfristig: {
    de: "kurzfristig",
    en: "at short notice",
    use: "Also short-term as a planning horizon: kurzfristig planen.",
    pos: "adjective",
  },
  morgen: {
    de: "morgen",
    en: "tomorrow",
    use: "Capitalised, der Morgen is the morning: heute Morgen = this morning; morgen früh = tomorrow morning.",
    pos: "adverb",
  },
  begründen: {
    de: "begründen",
    en: "to give reasons for",
    use: "To justify a decision by stating why: Kannst du das begründen? Founding something is also begründen in formal German.",
    pos: "verb",
  },
  knapp: {
    de: "knapp",
    en: "tight or barely enough",
    use: "knapp verloren = narrowly lost; eine knappe Stunde = just under an hour; das Geld ist knapp = money is tight.",
    pos: "adjective",
  },
  einschränken: {
    de: "einschränken",
    en: "to restrict or cut back",
    use: "sich einschränken = to tighten one's belt.",
    pos: "verb",
  },
  kündigung: {
    de: "die Kündigung",
    en: "termination or notice",
    use: "Of a job, a flat or a contract: die Kündigung einreichen = to hand in your notice.",
    pos: "noun",
  },
  übrig: {
    de: "übrig",
    en: "left over",
    use: "Ist noch was übrig? = is there any left? Übrig bleiben = to remain.",
    pos: "adjective",
  },
  gefährden: {
    de: "gefährden",
    en: "to endanger",
    use: "Den Erfolg gefährden = to jeopardise the outcome.",
    pos: "verb",
  },
  kündigen: {
    de: "kündigen",
    en: "to quit or cancel",
    use: "A job, a flat, a subscription: das Abo kündigen. With a person as object it means to dismiss them.",
    pos: "verb",
  },
  haltung: {
    de: "die Haltung",
    en: "posture or stance",
    use: "Physical posture at the desk, or your stance on an issue: eine klare Haltung.",
    pos: "noun",
  },
  störung: {
    de: "die Störung",
    en: "fault or disruption",
    use: "An outage (Störung im Netz), a malfunction, or entschuldigen Sie die Störung = sorry to disturb you.",
    pos: "noun",
  },
  sperren: {
    de: "sperren",
    en: "to block",
    use: "Eine Karte sperren lassen = to have a card blocked; eine Straße sperren = to close a road.",
    pos: "verb",
  },
  begründung: {
    de: "die Begründung",
    en: "reason given",
    use: "The justification attached to a decision: ohne Begründung = with no reason given.",
    pos: "noun",
  },
  ablaufen: {
    de: "ablaufen",
    en: "to expire",
    use: "Der Ausweis läuft ab = the ID expires. Also how something unfolds: Wie läuft das ab? = how does it work?",
    pos: "verb",
  },
  abbauen: {
    de: "abbauen",
    en: "to dismantle",
    use: "Take down the stage, cut jobs, or mine coal — all abbauen. Stress abbauen = to work off stress.",
    pos: "verb",
  },
  kritisieren: {
    de: "kritisieren",
    en: "to criticise",
    use: "Konstruktiv kritisieren = to give constructive criticism.",
    pos: "verb",
  },
  zeugnis: {
    de: "das Zeugnis",
    en: "school report or reference",
    use: "The end-of-year school report, or an employer's reference: das Arbeitszeugnis.",
    pos: "noun",
  },
  absichern: {
    de: "absichern",
    en: "to safeguard",
    use: "sich absichern = to cover yourself: schriftlich absichern = to get it in writing.",
    pos: "verb",
  },
  gutachten: {
    de: "das Gutachten",
    en: "expert report",
    use: "A commissioned expert assessment — for a flat, a car, a court case.",
    pos: "noun",
  },
  schneiden: {
    de: "schneiden",
    en: "to cut",
    use: "Chop vegetables, cut hair, or edit video — all schneiden. Sich schneiden = to cut yourself.",
    pos: "verb",
  },
  ungefähr: {
    de: "ungefähr",
    en: "roughly or about",
    use: "Ungefähr zehn Minuten = about ten minutes.",
    pos: "adverb",
  },
  hervorheben: {
    de: "hervorheben",
    en: "to highlight or emphasise",
    use: "Positiv hervorheben = to single out for praise.",
    pos: "verb",
  },
  filiale: {
    de: "die Filiale",
    en: "branch",
    use: "A shop's or bank's branch: die nächste Filiale = the nearest branch.",
    pos: "noun",
  },
  reichweite: {
    de: "die Reichweite",
    en: "range or reach",
    use: "An e-car's range, a network's coverage, or a post's reach online.",
    pos: "noun",
  },
  bewusstsein: {
    de: "das Bewusstsein",
    en: "consciousness or awareness",
    use: "Das Bewusstsein verlieren = to lose consciousness; im Bewusstsein, dass = aware that.",
    pos: "noun",
  },
  feierabend: {
    de: "der Feierabend",
    en: "end of the working day",
    use: "Feierabend machen = to knock off; schönen Feierabend! is the after-work goodbye.",
    pos: "noun",
  },
  vollpfosten: {
    de: "der Vollpfosten",
    en: "complete idiot",
    use: "Blunt insult, literally a full fencepost. Friends-only register.",
    pos: "noun",
  },
  korb: {
    de: "der Korb",
    en: "basket",
    use: "Einen Korb bekommen = to be turned down romantically — the idiom every learner meets.",
    pos: "noun",
  },
  griff: {
    de: "der Griff",
    en: "handle or grip",
    use: "Door handles and pan handles; etwas in den Griff bekommen = to get something under control.",
    pos: "noun",
  },
  einräumen: {
    de: "einräumen",
    en: "to put away or load",
    use: "Die Spülmaschine einräumen = to load the dishwasher. In argument, it means to concede a point.",
    pos: "verb",
  },
  nachvollziehen: {
    de: "nachvollziehen",
    en: "to follow someone's reasoning",
    use: "Ich kann das nachvollziehen = I can see how you got there — understanding, not agreement.",
    pos: "verb",
  },
  überspitzt: {
    de: "überspitzt",
    en: "exaggerated for effect",
    use: "Überspitzt gesagt = to put it pointedly.",
    pos: "adjective",
  },
  rückblickend: {
    de: "rückblickend",
    en: "in retrospect",
    use: "Rückblickend war es die richtige Entscheidung = looking back, it was right.",
    pos: "adverb",
  },
  vorwurf: {
    de: "der Vorwurf",
    en: "accusation or reproach",
    use: "Jemandem einen Vorwurf machen = to blame someone; kein Vorwurf! = no blame intended.",
    pos: "noun",
  },
  rückmeldung: {
    de: "die Rückmeldung",
    en: "feedback or reply",
    use: "Gib mir kurz Rückmeldung = let me know — the everyday word for a quick response.",
    pos: "noun",
  },
  absprache: {
    de: "die Absprache",
    en: "agreement or arrangement",
    use: "Nach Absprache = by arrangement; klare Absprachen treffen = to agree things clearly.",
    pos: "noun",
  },
  nachvollziehbar: {
    de: "nachvollziehbar",
    en: "understandable",
    use: "Reasoning you can follow: eine nachvollziehbare Entscheidung.",
    pos: "adjective",
  },
  abgabefrist: {
    de: "die Abgabefrist",
    en: "submission deadline",
    use: "For homework, tax returns and applications alike.",
    pos: "noun",
  },
  entkräften: {
    de: "entkräften",
    en: "to refute",
    use: "Ein Argument entkräften = to take the force out of an argument.",
    pos: "verb",
  },
  forschungsstand: {
    de: "der Forschungsstand",
    en: "state of research",
    use: "Der aktuelle Forschungsstand = what research currently says.",
    pos: "noun",
  },
  mist: {
    de: "der Mist",
    en: "darn or crap",
    use: "Mild expletive, literally manure: So ein Mist! = darn it! Mist bauen = to mess up.",
    pos: "noun",
  },
  verarschen: {
    de: "verarschen",
    en: "to take the piss out of someone",
    use: "Vulgar-casual: Willst du mich verarschen? = are you kidding me?",
    pos: "verb",
  },
  vertragen: {
    de: "vertragen",
    en: "to tolerate",
    use: "Ich vertrage keinen Kaffee = coffee doesn't agree with me. sich vertragen = to get along or make up.",
    pos: "verb",
  },
  heikel: {
    de: "heikel",
    en: "delicate or tricky",
    use: "Ein heikles Thema = a touchy subject.",
    pos: "adjective",
  },
  abhängigkeit: {
    de: "die Abhängigkeit",
    en: "dependence",
    use: "Also addiction in the clinical sense; in Abhängigkeit von = depending on.",
    pos: "noun",
  },
  hinterfragen: {
    de: "hinterfragen",
    en: "to question critically",
    use: "To probe what is behind a claim rather than doubt it outright.",
    pos: "verb",
  },
  aufwärmen: {
    de: "aufwärmen",
    en: "to warm up",
    use: "Food from yesterday (Essen aufwärmen) or muscles before sport (sich aufwärmen).",
    pos: "verb",
  },
  schminken: {
    de: "schminken",
    en: "to put on make-up",
    use: "sich schminken = to do one's make-up; abschminken = to take it off.",
    pos: "verb",
  },
  anstoßen: {
    de: "anstoßen",
    en: "to clink glasses",
    use: "Auf etwas anstoßen = to toast something. Also to nudge something into motion: eine Debatte anstoßen.",
    pos: "verb",
  },
  kater: {
    de: "der Kater",
    en: "hangover",
    use: "Einen Kater haben = to be hungover. Literally a tomcat — the male cat is also der Kater.",
    pos: "noun",
  },
  nüchtern: {
    de: "nüchtern",
    en: "sober",
    use: "Not drunk; before a blood test it means on an empty stomach: nüchtern kommen. A sober tone is also nüchtern.",
    pos: "adjective",
  },
  zocken: {
    de: "zocken",
    en: "to game",
    use: "Casual for playing video games; in money contexts it means to gamble.",
    pos: "verb",
  },
  widerlegen: {
    de: "widerlegen",
    en: "to disprove",
    use: "Eine Behauptung widerlegen = to show a claim is false.",
    pos: "verb",
  },
  trauzeuge: {
    de: "der Trauzeuge",
    en: "best man or wedding witness",
    use: "The legal witness at a German wedding, usually also the best man. Feminine: die Trauzeugin.",
    pos: "noun",
  },
  austreten: {
    de: "austreten",
    en: "to leave an organisation",
    use: "Aus der Kirche austreten = to formally leave the church. Casually, mal austreten = to nip to the loo.",
    pos: "verb",
  },
  aufhören: {
    de: "aufhören",
    en: "to stop",
    use: "Hör auf! = stop it! With mit: mit dem Rauchen aufhören = to quit smoking.",
    pos: "verb",
  },
  anbraten: {
    de: "anbraten",
    en: "to sear",
    use: "Brown meat or onions briefly at high heat before cooking on.",
    pos: "verb",
  },
  braten: {
    de: "braten",
    en: "to fry or roast",
    use: "In the pan or the oven. Der Braten (capitalised) is the roast itself.",
    pos: "verb",
  },
  abschmecken: {
    de: "abschmecken",
    en: "to season to taste",
    use: "Taste at the end and adjust: mit Salz und Pfeffer abschmecken.",
    pos: "verb",
  },
  fundbüro: {
    de: "das Fundbüro",
    en: "lost property office",
    use: "Where lost things end up — beim Fundbüro nachfragen = to ask at lost property.",
    pos: "noun",
  },
  kostenvoranschlag: {
    de: "der Kostenvoranschlag",
    en: "cost estimate",
    use: "The written quote a garage or tradesperson gives before work starts.",
    pos: "noun",
  },
  elfmeter: {
    de: "der Elfmeter",
    en: "penalty kick",
    use: "Football: Elfmeter schießen = to take a penalty; elf Meter from goal.",
    pos: "noun",
  },
  verlängerung: {
    de: "die Verlängerung",
    en: "extension",
    use: "Of a deadline or contract; in football it is extra time.",
    pos: "noun",
  },
  ausschlafen: {
    de: "ausschlafen",
    en: "to sleep in",
    use: "Endlich mal ausschlafen = to finally get a lie-in.",
    pos: "verb",
  },
  schulden: {
    de: "die Schulden",
    en: "debts",
    use: "Always plural: Schulden machen = to run up debts. The verb schulden = to owe: Was schulde ich dir?",
    pos: "noun",
  },
  trauerfeier: {
    de: "die Trauerfeier",
    en: "funeral service",
    use: "The ceremony itself; the burial is die Beerdigung.",
    pos: "noun",
  },
  ohrwurm: {
    de: "der Ohrwurm",
    en: "earworm",
    use: "A song stuck in your head: einen Ohrwurm haben.",
    pos: "noun",
  },
  mitbringsel: {
    de: "das Mitbringsel",
    en: "small gift for the host",
    use: "What you bring when invited — flowers, wine, chocolate.",
    pos: "noun",
  },
  kassenbon: {
    de: "der Kassenbon",
    en: "receipt",
    use: "The till slip; den Bon aufheben = to keep the receipt.",
    pos: "noun",
  },
  anschreiben: {
    de: "das Anschreiben",
    en: "cover letter",
    use: "The letter with a job application. The verb anschreiben = to message someone first.",
    pos: "noun",
  },
  arbeitszeugnis: {
    de: "das Arbeitszeugnis",
    en: "employer's reference",
    use: "The formal reference every German employee is entitled to on leaving.",
    pos: "noun",
  },
  zusage: {
    de: "die Zusage",
    en: "acceptance or confirmation",
    use: "The yes: die Zusage für den Job bekommen = to get the job offer confirmed.",
    pos: "noun",
  },
  nachliefern: {
    de: "nachliefern",
    en: "to deliver later",
    use: "A missing part follows separately: wird nachgeliefert = will follow.",
    pos: "verb",
  },
  garderobe: {
    de: "die Garderobe",
    en: "cloakroom or coat rack",
    use: "An die Garderobe geben = to hand in at the cloakroom.",
    pos: "noun",
  },
  deshalb: {
    de: "deshalb",
    en: "that's why",
    use: "Keeps normal word order: Ich bin müde, deshalb gehe ich = I'm tired, that's why I'm going.",
    pos: "connector",
  },
  deswegen: {
    de: "deswegen",
    en: "that's why",
    use: "Interchangeable with deshalb in everyday speech.",
    pos: "connector",
  },
  infolgedessen: {
    de: "infolgedessen",
    en: "as a result",
    use: "Formal, written register — everyday speech says deshalb.",
    pos: "connector",
  },
  trotzdem: {
    de: "trotzdem",
    en: "nevertheless or anyway",
    use: "Danke trotzdem = thanks anyway.",
    pos: "connector",
  },
  allerdings: {
    de: "allerdings",
    en: "however or mind you",
    use: "Softens a contrast: Gut ist es, allerdings teuer. As an answer it means definitely.",
    pos: "connector",
  },
  fertigkeit: {
    de: "die Fertigkeit",
    en: "practical skill",
    use: "A trainable ability — die vier Fertigkeiten in language learning are the four skills.",
    pos: "noun",
  },
  aufladen: {
    de: "aufladen",
    en: "to charge up",
    use: "Phones, cards and batteries: das Handy aufladen; Guthaben aufladen = to top up credit.",
    pos: "verb",
  },
  blockieren: {
    de: "blockieren",
    en: "to block",
    use: "A blocked road, a blocked user, or a jammed mechanism: die Tür blockiert.",
    pos: "verb",
  },
  zufall: {
    de: "der Zufall",
    en: "coincidence",
    use: "So ein Zufall! = what a coincidence! Durch Zufall = by chance.",
    pos: "noun",
  },
  übertreiben: {
    de: "übertreiben",
    en: "to exaggerate",
    use: "Jetzt übertreib mal nicht = don't overdo it.",
    pos: "verb",
  },
  einpacken: {
    de: "einpacken",
    en: "to pack or wrap",
    use: "Pack a bag or wrap a present: als Geschenk einpacken = to gift-wrap.",
    pos: "verb",
  },
  buntwäsche: {
    de: "die Buntwäsche",
    en: "coloured wash",
    use: "The colours load, washed separately from whites (die Kochwäsche).",
    pos: "noun",
  },
  futter: {
    de: "das Futter",
    en: "animal feed",
    use: "Pet food; in a jacket, das Futter is the lining.",
    pos: "noun",
  },
  leine: {
    de: "die Leine",
    en: "lead or line",
    use: "The dog's leash (an die Leine nehmen) or the washing line.",
    pos: "noun",
  },
  kratzen: {
    de: "kratzen",
    en: "to scratch",
    use: "An itchy jumper kratzt; the cat kratzt too.",
    pos: "verb",
  },
  entwerten: {
    de: "entwerten",
    en: "to validate a ticket",
    use: "Stamp the ticket in the machine before travelling; vergessen zu entwerten counts as riding without one.",
    pos: "verb",
  },
  steckdose: {
    de: "die Steckdose",
    en: "power socket",
    use: "Where der Stecker (the plug) goes in.",
    pos: "noun",
  },
  tagesablauf: {
    de: "der Tagesablauf",
    en: "daily routine",
    use: "How your day is structured, morning to night.",
    pos: "noun",
  },
  meistens: {
    de: "meistens",
    en: "usually or mostly",
    use: "Meistens klappt es = it usually works out.",
    pos: "adverb",
  },
  aufteilen: {
    de: "aufteilen",
    en: "to divide up",
    use: "Split tasks, costs or a pizza: Wir teilen uns das auf = we'll split it between us.",
    pos: "verb",
  },
  abschlag: {
    de: "der Abschlag",
    en: "instalment or deduction",
    use: "The monthly part-payment on utilities; in pensions, a deduction for retiring early.",
    pos: "noun",
  },
  nachzahlung: {
    de: "die Nachzahlung",
    en: "back payment",
    use: "What you still owe after the annual utility statement — the dreaded counterpart of the refund.",
    pos: "noun",
  },
  borgen: {
    de: "borgen",
    en: "to lend or borrow informally",
    use: "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.",
    pos: "verb",
  },
  azubi: {
    de: "der Azubi",
    en: "trainee",
    use: "Short for Auszubildender — someone in a formal apprenticeship. Feminine: die Azubi.",
    pos: "noun",
  },
  abkürzung: {
    de: "die Abkürzung",
    en: "shortcut or abbreviation",
    use: "A shorter route (eine Abkürzung nehmen) or a shortened word.",
    pos: "noun",
  },
  nacken: {
    de: "der Nacken",
    en: "back of the neck",
    use: "The back of the neck: ein steifer Nacken = a stiff neck.",
    pos: "noun",
  },
  aufklaren: {
    de: "aufklaren",
    en: "to clear up",
    use: "Weather only: Es klart auf = the sky is clearing. Explaining is aufklären, with umlaut.",
    pos: "verb",
  },
  durchhalten: {
    de: "durchhalten",
    en: "to hold out or keep going",
    use: "Halte durch! = hang in there!",
    pos: "verb",
  },
  deckel: {
    de: "der Deckel",
    en: "lid",
    use: "On a pot or jar; in a pub, auf den Deckel = on the tab.",
    pos: "noun",
  },
  läuse: {
    de: "die Läuse",
    en: "head lice",
    use: "Plural; one is die Laus. The kindergarten letter every parent dreads.",
    pos: "noun",
  },
  erstatten: {
    de: "erstatten",
    en: "to refund",
    use: "Die Kosten werden erstattet = the costs are reimbursed. Anzeige erstatten = to file a police report.",
    pos: "verb",
  },
  personalausweis: {
    de: "der Personalausweis",
    en: "identity card",
    use: "The German ID card — der Perso in casual speech.",
    pos: "noun",
  },
  anzahlung: {
    de: "die Anzahlung",
    en: "down payment",
    use: "The deposit paid up front: eine Anzahlung leisten.",
    pos: "noun",
  },
  umstellen: {
    de: "umstellen",
    en: "to switch over or rearrange",
    use: "Change a system (auf Sommerzeit umstellen), rearrange furniture, or adjust habits: die Ernährung umstellen.",
    pos: "verb",
  },
  chip: {
    de: "der Chip",
    en: "chip or token",
    use: "The trolley token, the microchip in the pet, and crisps: die Chips.",
    pos: "noun",
  },
  vorsatz: {
    de: "der Vorsatz",
    en: "resolution or intention",
    use: "Gute Vorsätze fürs neue Jahr = New Year's resolutions. In law, mit Vorsatz = with intent.",
    pos: "noun",
  },
  zuschlag: {
    de: "der Zuschlag",
    en: "surcharge",
    use: "The extra fee on fast trains; den Zuschlag bekommen = to be awarded the flat or contract.",
    pos: "noun",
  },
  waschprogramm: {
    de: "das Waschprogramm",
    en: "wash cycle",
    use: "Which programme the machine runs — Feinwäsche, 30 Grad.",
    pos: "noun",
  },
  liege: {
    de: "die Liege",
    en: "lounger",
    use: "Sun lounger by the pool or the daybed at the doctor's.",
    pos: "noun",
  },
  leerung: {
    de: "die Leerung",
    en: "collection",
    use: "When the postbox is emptied: nächste Leerung 17 Uhr.",
    pos: "noun",
  },
  überreden: {
    de: "überreden",
    en: "to talk someone into it",
    use: "Persuading into an action; changing a mind with reasons is überzeugen.",
    pos: "verb",
  },
  befund: {
    de: "der Befund",
    en: "medical finding",
    use: "What the examination showed: ohne Befund = all clear.",
    pos: "noun",
  },
  zettel: {
    de: "der Zettel",
    en: "slip of paper",
    use: "A note you write or the slip you are handed: der Einkaufszettel = shopping list.",
    pos: "noun",
  },
  einwerfen: {
    de: "einwerfen",
    en: "to post or drop in",
    use: "Den Brief einwerfen = to drop the letter in the box; also to throw in a remark.",
    pos: "verb",
  },
  rollator: {
    de: "der Rollator",
    en: "wheeled walker",
    use: "The walking frame on wheels.",
    pos: "noun",
  },
  abspann: {
    de: "der Abspann",
    en: "closing credits",
    use: "The credits at the end — nach dem Abspann = after the credits.",
    pos: "noun",
  },
  mittagsschlaf: {
    de: "der Mittagsschlaf",
    en: "midday nap",
    use: "Mittagsschlaf machen = to have an after-lunch nap.",
    pos: "noun",
  },
  anprobe: {
    de: "die Anprobe",
    en: "fitting",
    use: "Trying clothes on — zur Anprobe = for a fitting.",
    pos: "noun",
  },
  abstieg: {
    de: "der Abstieg",
    en: "descent",
    use: "The way down a mountain; in football, relegation.",
    pos: "noun",
  },
  aufstieg: {
    de: "der Aufstieg",
    en: "ascent or rise",
    use: "The climb up; also promotion — beruflicher Aufstieg, and promotion in football.",
    pos: "noun",
  },
  notdienst: {
    de: "der Notdienst",
    en: "emergency service",
    use: "The out-of-hours rota: die Apotheke hat Notdienst = the pharmacy is on emergency duty.",
    pos: "noun",
  },
  quote: {
    de: "die Quote",
    en: "rate or quota",
    use: "Viewing figures (die Einschaltquote), a required share, or betting odds.",
    pos: "noun",
  },
  sitzenbleiben: {
    de: "sitzenbleiben",
    en: "to repeat a school year",
    use: "Held back a year for failing grades; literally to stay seated.",
    pos: "verb",
  },
  mitgefühl: {
    de: "das Mitgefühl",
    en: "compassion",
    use: "Mein Mitgefühl = you have my sympathy.",
    pos: "noun",
  },
  untertitel: {
    de: "der Untertitel",
    en: "subtitle",
    use: "Usually plural: mit Untertiteln schauen = to watch with subtitles.",
    pos: "noun",
  },
  abmahnung: {
    de: "die Abmahnung",
    en: "formal warning",
    use: "The written warning from an employer or lawyer — one step before consequences.",
    pos: "noun",
  },
  vertretung: {
    de: "die Vertretung",
    en: "stand-in or cover",
    use: "The substitute teacher, the locum doctor: die Vertretung übernehmen = to cover.",
    pos: "noun",
  },
  rate: {
    de: "die Rate",
    en: "instalment",
    use: "Auf Raten kaufen = to buy in instalments; die monatliche Rate = the monthly payment.",
    pos: "noun",
  },
  winterdienst: {
    de: "der Winterdienst",
    en: "winter road clearing",
    use: "Gritting and snow-clearing — and the householder's duty to clear the pavement.",
    pos: "noun",
  },
  wadenwickel: {
    de: "der Wadenwickel",
    en: "calf compress",
    use: "The classic German home remedy for fever: damp cloths around the calves.",
    pos: "noun",
  },
  krankmelden: {
    de: "sich krankmelden",
    en: "to call in sick",
    use: "Ich habe mich krankgemeldet = I called in sick. The doctor's note is die Krankmeldung.",
    pos: "verb",
  },
  ausfall: {
    de: "der Ausfall",
    en: "cancellation or outage",
    use: "A cancelled lesson, a power failure, a server outage — all der Ausfall.",
    pos: "noun",
  },
  stundenlohn: {
    de: "der Stundenlohn",
    en: "hourly wage",
    use: "What you earn per hour worked.",
    pos: "noun",
  },
  spielraum: {
    de: "der Spielraum",
    en: "leeway",
    use: "Room to manoeuvre in a plan, budget or negotiation.",
    pos: "noun",
  },
  vorläufig: {
    de: "vorläufig",
    en: "provisional",
    use: "For now, until something final: vorläufige Ergebnisse = provisional results.",
    pos: "adjective",
  },
  schuld: {
    de: "schuld",
    en: "at fault",
    use: "Du bist schuld = it's your fault — never capitalised there. Die Schuld is the blame or guilt itself.",
    pos: "adjective",
  },
  geringfügig: {
    de: "geringfügig",
    en: "slight or marginal",
    use: "Also the mini-job sense: geringfügig beschäftigt = marginally employed.",
    pos: "adjective",
  },
  aufschlussreich: {
    de: "aufschlussreich",
    en: "revealing or insightful",
    use: "Ein aufschlussreiches Gespräch = a conversation that told you a lot.",
    pos: "adjective",
  },
  verhältnismäßig: {
    de: "verhältnismäßig",
    en: "relatively",
    use: "Verhältnismäßig günstig = comparatively cheap. In law it means proportionate.",
    pos: "adverb",
  },
  pauschal: {
    de: "pauschal",
    en: "flat-rate or sweeping",
    use: "A flat charge (pauschal 20 Euro) or an over-general claim: pauschale Aussagen.",
    pos: "adjective",
  },
  sachlich: {
    de: "sachlich",
    en: "objective or matter-of-fact",
    use: "Bleib sachlich = stick to the facts, keep emotion out.",
    pos: "adjective",
  },
  einordnen: {
    de: "einordnen",
    en: "to classify or put into context",
    use: "Etwas einordnen können = to know what to make of it; sich einordnen = to get in lane.",
    pos: "verb",
  },
  gegenüberstellen: {
    de: "gegenüberstellen",
    en: "to compare side by side",
    use: "Set two things against each other to compare them.",
    pos: "verb",
  },
  reichlich: {
    de: "reichlich",
    en: "plenty of",
    use: "Reichlich Zeit = plenty of time; eine reichliche Stunde = a good hour.",
    pos: "adjective",
  },
  rücksichtslos: {
    de: "rücksichtslos",
    en: "inconsiderate or reckless",
    use: "From rücksichtslos parken to reckless driving — no regard for others.",
    pos: "adjective",
  },
  gelassen: {
    de: "gelassen",
    en: "calm and composed",
    use: "Bleib gelassen = stay relaxed; gelassen reagieren = to take it in your stride.",
    pos: "adjective",
  },
  priorisieren: {
    de: "priorisieren",
    en: "to prioritise",
    use: "Aufgaben priorisieren = to rank tasks by importance.",
    pos: "verb",
  },
  beibehalten: {
    de: "beibehalten",
    en: "to keep or stick with",
    use: "Den Kurs beibehalten = to stay the course; eine Gewohnheit beibehalten.",
    pos: "verb",
  },
  nachlassen: {
    de: "nachlassen",
    en: "to ease off or wane",
    use: "Der Regen lässt nach = the rain is easing; die Konzentration lässt nach.",
    pos: "verb",
  },
  beheben: {
    de: "beheben",
    en: "to fix",
    use: "Einen Fehler beheben = to fix a fault; der Schaden ist behoben.",
    pos: "verb",
  },
  verzögerung: {
    de: "die Verzögerung",
    en: "delay or hold-up",
    use: "Mit Verzögerung = with a delay; in tech, latency.",
    pos: "noun",
  },
  vorbeugen: {
    de: "vorbeugen",
    en: "to guard against",
    use: "Vorbeugen ist besser als heilen = prevention beats cure. Takes dative: Krankheiten vorbeugen.",
    pos: "verb",
  },
  schwül: {
    de: "schwül",
    en: "muggy",
    use: "Heavy, humid summer air before a storm.",
    pos: "adjective",
  },
  durchschlafen: {
    de: "durchschlafen",
    en: "to sleep through the night",
    use: "Das Baby schläft endlich durch = the baby finally sleeps through.",
    pos: "verb",
  },
  ziel: {
    de: "das Ziel",
    en: "goal or aim",
    use: "Also the destination when travelling and the finish line in a race: am Ziel = at the finish.",
    pos: "noun",
  },
  weg: {
    de: "der Weg",
    en: "way or path",
    use: "Auf dem Weg = on the way; sich auf den Weg machen = to set off. Not to confuse with weg = gone.",
    pos: "noun",
  },
  bestehen: {
    de: "bestehen",
    en: "to pass",
    use: "Eine Prüfung bestehen = to pass an exam. bestehen aus = to consist of; auf etwas bestehen = to insist on it.",
    pos: "verb",
  },
  gemeinde: {
    de: "die Gemeinde",
    en: "community",
    use: "The local-government unit; a church congregation is also die Gemeinde.",
    pos: "noun",
  },
  anwendung: {
    de: "die Anwendung",
    en: "application or use",
    use: "Software calls a program eine Anwendung; at a spa it is a treatment.",
    pos: "noun",
  },
  gleich: {
    de: "gleich",
    en: "in a moment",
    use: "Bis gleich! = see you in a bit. As an adjective it means the same: der gleiche Film.",
    pos: "adverb",
  },
  prozess: {
    de: "der Prozess",
    en: "process",
    use: "A court trial is also der Prozess: vor Gericht stehen, einen Prozess führen.",
    pos: "noun",
  },
  alter: {
    de: "das Alter",
    en: "age",
    use: "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.",
    pos: "noun",
  },
  tipp: {
    de: "der Tipp",
    en: "tip or hint",
    use: "Ein guter Tipp = a good tip. In the lottery, your Tipp is the numbers you picked.",
    pos: "noun",
  },
  vertreten: {
    de: "vertreten",
    en: "to represent or stand in for",
    use: "Die Kollegin vertritt mich = my colleague is covering for me; eine Meinung vertreten = to hold a view.",
    pos: "verb",
  },
  ausgehen: {
    de: "ausgehen",
    en: "to go out",
    use: "Heute Abend ausgehen = to go out tonight. Wie ist es ausgegangen? = how did it turn out? Mir geht das Geld aus = I'm running out of money.",
    pos: "verb",
  },
  einstellen: {
    de: "einstellen",
    en: "to set or adjust",
    use: "Die Heizung einstellen = to set the heating. Also to hire someone, and sich einstellen auf = to prepare for.",
    pos: "verb",
  },
  feld: {
    de: "das Feld",
    en: "field",
    use: "A farmer's field, a form field, or a square on a board game.",
    pos: "noun",
  },
  aufnahme: {
    de: "die Aufnahme",
    en: "recording",
    use: "Audio, photo or film; also admission — die Aufnahme ins Krankenhaus.",
    pos: "noun",
  },
  maschine: {
    de: "die Maschine",
    en: "machine",
    use: "Also the washing machine (die Maschine anstellen), a plane, and the barber's clippers.",
    pos: "noun",
  },
  kurs: {
    de: "der Kurs",
    en: "course",
    use: "A class you take (einen Kurs belegen), an exchange rate, and a ship's heading.",
    pos: "noun",
  },
  strecke: {
    de: "die Strecke",
    en: "route or distance",
    use: "Die Strecke nach Hause = the way home; a running route; auf der Strecke bleiben = to fall by the wayside.",
    pos: "noun",
  },
  drehen: {
    de: "drehen",
    en: "to turn",
    use: "Turn something around, shoot a film (einen Film drehen), or roll a cigarette (selber drehen).",
    pos: "verb",
  },
  träger: {
    de: "der Träger",
    en: "strap or carrier",
    use: "The strap on a dress or bag; institutionally, the organisation that runs a Kita or clinic.",
    pos: "noun",
  },
  ausfallen: {
    de: "ausfallen",
    en: "to be cancelled",
    use: "Die Stunde fällt aus = the lesson is off. Also to fail (die Heizung ist ausgefallen) and to turn out: gut ausfallen.",
    pos: "verb",
  },
  anschließen: {
    de: "anschließen",
    en: "to connect",
    use: "Plug in a device; lock a bike to something; sich anschließen = to join in.",
    pos: "verb",
  },
  abhängen: {
    de: "abhängen",
    en: "to depend on",
    use: "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.",
    pos: "verb",
  },
  zug: {
    de: "der Zug",
    en: "train",
    use: "Den Zug nehmen = to take the train. Also a move in a game (du bist am Zug) and a draught: es zieht.",
    pos: "noun",
  },
  ausführen: {
    de: "ausführen",
    en: "to carry out or execute",
    use: "Execute a plan or an order; näher ausführen = to elaborate; den Hund ausführen = to walk the dog.",
    pos: "verb",
  },
  regelung: {
    de: "die Regelung",
    en: "rule or arrangement",
    use: "The agreed way something is handled: eine klare Regelung finden.",
    pos: "noun",
  },
  eingehen: {
    de: "eingehen",
    en: "to respond to",
    use: "auf etwas eingehen = to engage with it. Clothes shrink (das T-Shirt ist eingegangen); plants die the same way.",
    pos: "verb",
  },
  einführen: {
    de: "einführen",
    en: "to introduce",
    use: "Bring in something new: eine Regel einführen. Trade sense: to import.",
    pos: "verb",
  },
  kommentar: {
    de: "der Kommentar",
    en: "comment",
    use: "Kein Kommentar = no comment. In the press, a Kommentar is an opinion column.",
    pos: "noun",
  },
  anzeige: {
    de: "die Anzeige",
    en: "advert or police report",
    use: "Eine Anzeige schalten = to place an ad; Anzeige erstatten = to report someone to the police.",
    pos: "noun",
  },
};

const senseKey = (value: string) => String(value ?? "").trim().toLocaleLowerCase("de-DE");

export function canonicalWordSenseFor(lookup: string): CanonicalWordSense | undefined {
  return REVIEWED_WORD_SENSES[senseKey(lookup)];
}

export const REVIEWED_CANONICAL_WORDS = Object.freeze(Object.keys(REVIEWED_WORD_SENSES));
