import { CURRICULUM_ORDER, packMeta } from "@/lib/curriculum";

/**
 * The packs that give a learner the fastest route into a normal conversation.
 *
 * This order is deliberately authored rather than inferred from individual
 * word counts. A sentence full of common words is not automatically a useful
 * thing to learn early ("I was flashed by a speed camera" is the motivating
 * example). These packs cover opening a conversation, repairing it, reacting,
 * making simple plans and keeping the exchange moving.
 */
const CONVERSATION_ESSENTIAL_PACKS = [
  "cb-greetings",
  "cb-introductions",
  "part1",
  // The building blocks longer sentences grow from. Being in tier 1 of
  // CURRICULUM_ORDER was not enough: the band comes from THIS list, and
  // without an entry here the bases scored band 4 — ranked below the very
  // sentences they are supposed to introduce, so the chains never surfaced.
  "part533",
  "cb-conversation-repair",
  "cb-reactions",
  "cb-shortreplies",
  "part158",
  "part160",
  "part534",
  "part161",
  "part169",
  "part171",
  "cb-smalltalk",
  "part57",
  "part150",
  "cb-plans",
  "part4",
  "part162",
  "part163",
  "part164",
] as const;

/** Common next-step topics once the learner can keep a conversation alive. */
const EVERYDAY_CONVERSATION_PACKS = [
  "part165",
  "part166",
  "part167",
  "part168",
  "part170",
  "part244",
  "cb-conversation-bridges",
  "cb-opinions",
  "cb-numbers-time",
  "cb-letters-numbers",
  "part2",
  "cb-directions",
  "part6",
  "cb-travel",
  "cb-food",
  "part5",
  "cb-shopping",
  "cb-grocery",
  "cb-money",
  "part3",
  "cb-routine",
  "part7",
  "cb-family",
  "cb-weather",
  "cb-connectors",
  "cb-health",
  "cb-emergencies",
] as const;

/**
 * The usefulness bands as a filter offers them, in the order they are offered.
 *
 * Here rather than in a tracker because both trackers offer it: usefulness is
 * read from the pack an item belongs to, and words belong to packs exactly as
 * sentences do. Kept as one list so the two cannot drift into offering
 * different bands for the same underlying value.
 */
export const USEFULNESS_FILTERS: { key: "all" | ConversationUsefulness; label: string }[] = [
  { key: "all", label: "All usefulness levels" },
  { key: "essential", label: "Conversation essentials" },
  { key: "everyday", label: "Everyday conversation" },
  { key: "personal", label: "Your material" },
  { key: "daily", label: "Daily life" },
  { key: "occasional", label: "Now and then" },
  { key: "life-event", label: "Life events & big topics" },
  // The band every pack falls back to, and by a wide margin the largest — a
  // third of everything teachable. It was the one band with no way to ask for
  // it, so choosing any band at all silently excluded most of the catalogue
  // and no combination of the others added back up to the whole.
  { key: "situational", label: "Situational" },
  { key: "specialist", label: "Specialist / casual" },
  { key: "extra", label: "Extra practice" },
];

export type ConversationUsefulness =
  | "essential"
  | "personal"
  | "everyday"
  | "daily"
  | "occasional"
  | "life-event"
  | "situational"
  | "specialist"
  | "extra";

export type ConversationPriorityInfo = {
  key: ConversationUsefulness;
  label: string;
  hint: string;
  band: number;
  packRank: number;
};

type ConversationPriorityInput = {
  partKey?: string;
  kind?: "vocab" | "phrase" | "dialogue";
  /** sentenceCommonality result: lower means more common vocabulary */
  commonality?: number;
  /** authored nudge inside a pack: lower means teach sooner */
  lessonPriority?: number;
  /**
   * The learner has marked this item's pack as one they have little interest
   * in (see packInterest.ts) — cooking, say, for somebody who never cooks.
   * Not the same as the item being unusual: "Ich habe die Ausbildung
   * abgebrochen" can be rare AND wanted, but every sentence about ovens and
   * boiling water is unwanted regardless of how common it is. So this sits
   * outside the band-and-commonality scoring below it, pushed past every
   * band there is, rather than folded into commonality where a common word
   * from an uninteresting pack would still win.
   */
  deprioritized?: boolean;
};

/**
 * The situational middle, split by how often the situation actually arises.
 *
 * 309 of 373 packs used to share one band, so once a learner was past the
 * ~1,200 essential and everyday items the band stopped sorting anything and
 * order fell to word-frequency alone — which is how a pregnancy-and-parental-
 * leave line could arrive before "where is the toilet". Frequency of NEED is
 * an editorial judgement no word count can supply, so it is written down here.
 *
 * Generated by scratchpad/classify-packs.cjs and checked in deliberately: an
 * explicit list can be argued with, a runtime keyword match cannot.
 */
const DAILY_LIFE_PACKS = [
  "part8",
  "part9",
  "part10",
  "part15",
  "part23",
  "part24",
  "part35",
  "part49",
  "part51",
  "part63",
  "part65",
  "part68",
  "part69",
  "part70",
  "part71",
  "part72",
  "part73",
  "part74",
  "part75",
  "part76",
  "part78",
  "part79",
  "part80",
  "part82",
  "part83",
  "part85",
  "part87",
  "part90",
  "part91",
  "part93",
  "part94",
  "part101",
  "part103",
  "part104",
  "part105",
  "part106",
  "part107",
  "part108",
  "part109",
  "part110",
  "part112",
  "part113",
  "part114",
  "part116",
  "part117",
  "part119",
  "part120",
  "part123",
  "part126",
  "part129",
  "part130",
  "part134",
  "part136",
  "part137",
  "part140",
  "part142",
  "part178",
  "part180",
  "part182",
  "part185",
  "part187",
  "part192",
  "part194",
  "part195",
  "part196",
  "part199",
  "part200",
  "part203",
  "part206",
  "part208",
  "part209",
  "part210",
  "part211",
  "part212",
  "part223",
  "part225",
  "part226",
  "part237",
  "part238",
  "part250",
  "part251",
  "part253",
  "part254",
  "part257",
  "part302",
  "part315",
  "part329",
  "part340",
  "part370",
  // From the curated phrasebank, which the first pass never reached:
  "cb-work",
  "cb-phone",
  "cb-emotions",
  "cb-housing",
  "cb-social",
  "cb-german-rules",
  "cb-post-packages",
  "cb-diet-allergies",
  "cb-apartment-repairs",
  "cb-internet-support",
  "cb-body-skin",
];

/** Comes up now and then rather than most weeks. */
const OCCASIONAL_PACKS = [
  "part11",
  "part12",
  "part21",
  "part36",
  "part43",
  "part58",
  "part59",
  "part53",
  "part61",
  "part62",
  "part64",
  "part67",
  "part77",
  "part81",
  "part84",
  "part86",
  "part88",
  "part89",
  "part95",
  "part96",
  "part98",
  "part99",
  "part100",
  "part102",
  "part111",
  "part115",
  "part118",
  "part121",
  "part122",
  "part124",
  "part125",
  "part128",
  "part131",
  "part132",
  "part133",
  "part135",
  "part138",
  "part139",
  "part141",
  "part144",
  "part145",
  "part151",
  "part152",
  "part154",
  "part155",
  "part156",
  "part157",
  "part159",
  "part172",
  "part173",
  "part174",
  "part175",
  "part176",
  "part177",
  "part179",
  "part181",
  "part183",
  "part184",
  "part186",
  "part189",
  "part191",
  "part193",
  "part198",
  "part201",
  "part202",
  "part204",
  "part205",
  "part207",
  "part214",
  "part215",
  "part216",
  "part217",
  "part218",
  "part219",
  "part220",
  "part222",
  "part224",
  "part227",
  "part228",
  "part229",
  "part230",
  "part231",
  "part232",
  "part233",
  "part234",
  "part242",
  "part243",
  "part245",
  "part246",
  "part247",
  "part252",
  "part255",
  "part259",
  "part260",
  "part261",
  "part263",
  "part264",
  "part265",
  "part266",
  "part267",
  "part268",
  "part300",
  "part301",
  "part303",
  "part304",
  "part305",
  "part306",
  "part307",
  "part308",
  "part309",
  "part310",
  "part311",
  "part312",
  "part313",
  "part314",
  "part316",
  "part317",
  "part318",
  "part319",
  "part320",
  "part321",
  "part322",
  "part323",
  "part324",
  "part325",
  "part326",
  "part327",
  "part328",
  "part330",
  "part331",
  "part332",
  "part333",
  "part334",
  "part335",
  "part336",
  "part337",
  "part338",
  "part339",
  "part341",
  "part342",
  "part343",
  "part344",
  "part345",
  "part346",
  "part347",
  "part348",
  "part349",
  "part350",
  "part351",
  "part352",
  "part353",
  "part354",
  "part359",
  "part356",
  "part358",
  "part355",
  "part357",
  "part360",
  "part364",
  "part363",
  "part365",
  "part361",
  "part368",
  "part366",
  "part369",
  "part371",
  "part367",
  "part374",
  "part372",
  "part373",
  "part375",
  "part377",
  "part376",
  "part379",
  "part378",
  "part380",
  // From the curated phrasebank:
  "cb-hotel",
  "cb-train-travel",
  "cb-driving",
  "cb-hobbies",
  "cb-celebrations",
  "cb-amt",
  "cb-pets-animals",
  "cb-kids-school",
  "cb-beer-culture",
  "cb-nightlife",
  "cb-football-culture",
  "cb-flea-markets",
  "cb-barber-requests",
  "cb-gardening-plants",
  "cb-medical-bureaucracy",
  "cb-traffic-fines",
];

/** Rare life events, heavy subjects and specific interests. */
const LIFE_EVENT_PACKS = [
  "part18",
  "part22",
  "part25",
  "part26",
  "part27",
  "part30",
  "part32",
  "part33",
  "part34",
  "part37",
  "part38",
  "part39",
  "part40",
  "part41",
  "part44",
  "part46",
  "part47",
  "part48",
  "part50",
  "part55",
  "part56",
  "part52",
  "part54",
  "part60",
  "part66",
  "part92",
  "part127",
  "part143",
  "part188",
  "part190",
  "part197",
  "part213",
  "part221",
  "part235",
  "part236",
  "part239",
  "part240",
  "part241",
  "part248",
  "part249",
  "part256",
  "part258",
  "part262",
  "part362",
  // From the curated phrasebank:
  "cb-dating",
  "cb-finance-insurance",
  "cb-family-problems",
  "cb-dreams-aspirations",
  "cb-money-woes",
  "cb-salary-negotiations",
];

const essentialRank = new Map<string, number>(
  CONVERSATION_ESSENTIAL_PACKS.map((key, index) => [key, index])
);
const everydayRank = new Map<string, number>(
  EVERYDAY_CONVERSATION_PACKS.map((key, index) => [key, index])
);
const curriculumRank = new Map<string, number>(
  CURRICULUM_ORDER.map((key, index) => [key, index])
);

const dailyRank = new Map<string, number>(DAILY_LIFE_PACKS.map((key, index) => [key, index]));
const occasionalRank = new Map<string, number>(OCCASIONAL_PACKS.map((key, index) => [key, index]));
const lifeEventRank = new Map<string, number>(LIFE_EVENT_PACKS.map((key, index) => [key, index]));

function fallbackRank(partKey: string) {
  const known = curriculumRank.get(partKey);
  if (known != null) return known;
  const tatoeba = /^tatoeba-(a1|a2|b1|b2)-(\d+)$/i.exec(partKey);
  if (tatoeba) {
    const levelRank = ["a1", "a2", "b1", "b2"].indexOf(tatoeba[1].toLowerCase());
    return Math.max(0, levelRank) * 1_000 + Number(tatoeba[2] || 0);
  }
  return CURRICULUM_ORDER.length + 5_000;
}

/**
 * Honest, learner-facing usefulness category for an item.
 *
 * "Most common" in the tracker uses this category first, then the authored
 * pack order, then sentence-level frequency. It never promotes a niche corpus
 * sentence merely because its individual words happen to be frequent.
 */
export function conversationPriorityInfo(partKeyValue: string | undefined): ConversationPriorityInfo {
  const partKey = String(partKeyValue ?? "");

  if (partKey.startsWith("mine-")) {
    return {
      key: "personal",
      label: "Your material",
      hint: "Content you added yourself, kept near the front because it matters to you.",
      band: 1,
      packRank: fallbackRank(partKey),
    };
  }

  if (partKey.startsWith("tatoeba")) {
    return {
      key: "extra",
      label: "Extra practice",
      hint: "A broader real-sentence library for later practice, not an early conversation essential.",
      band: 7,
      packRank: fallbackRank(partKey),
    };
  }

  const essential = essentialRank.get(partKey);
  if (essential != null) {
    return {
      key: "essential",
      label: "Conversation essential",
      hint: "One of the first phrases to learn for starting, repairing or continuing a normal conversation.",
      band: 0,
      packRank: essential,
    };
  }

  const everyday = everydayRank.get(partKey);
  if (everyday != null) {
    return {
      key: "everyday",
      label: "Everyday conversation",
      hint: "Common next-step language for ordinary plans, people, places and daily needs.",
      band: 2,
      packRank: everyday,
    };
  }

  const meta = packMeta(partKey);
  if (meta.tier === 3) {
    return {
      key: "specialist",
      label: "Specialist / casual",
      hint: "Useful in a narrower, regional, technical or very casual context.",
      band: 6,
      packRank: fallbackRank(partKey),
    };
  }

  // The three bands below replace what used to be one "situational" bucket
  // holding 309 of 373 packs — so wide that past the essentials it sorted
  // nothing, and order fell to word frequency alone.
  const daily = dailyRank.get(partKey);
  if (daily != null) {
    return {
      key: "daily",
      label: "Daily life",
      hint: "Comes up most weeks: getting around, eating, working, feeling rough, talking to people.",
      band: 3,
      packRank: daily,
    };
  }

  const occasional = occasionalRank.get(partKey);
  if (occasional != null) {
    return {
      key: "occasional",
      label: "Now and then",
      hint: "Comes up sometimes — travel, appointments, hobbies, sport, screens, paperwork.",
      band: 4,
      packRank: occasional,
    };
  }

  const lifeEvent = lifeEventRank.get(partKey);
  if (lifeEvent != null) {
    return {
      key: "life-event",
      label: "Life events & big topics",
      hint: "Weddings, loss, politics, money worries and other things you meet rarely but need real words for.",
      band: 5,
      packRank: lifeEvent,
    };
  }

  return {
    key: "situational",
    label: "Situational",
    hint: "Useful when this situation comes up, after the main conversation essentials.",
    band: 4,
    packRank: fallbackRank(partKey) + (meta.tier === 2 ? 1_000 : 0),
  };
}

/**
 * Stable ascending score used by lessons, the tracker and pet recall.
 *
 * Category bands stay hard boundaries — essentials always come before
 * everyday material, and both before situational packs. INSIDE a band,
 * how common the sentence actually is drives the order: the guided flow
 * promises "what people say most, first", and authored pack order used to
 * override that (packRank * 10,000 dwarfed commonality's 0-5,000 range), so
 * reaching a niche pack pushed lines like "Ich war ein totaler Streber" ahead
 * of thousands of more common unseen phrases. Now an author's lessonPriority
 * can still deliberately promote or demote an item, phrases still edge out
 * vocabulary examples at equal commonality, and pack order is only the final
 * tie-break for lesson coherence.
 */
export function conversationPriorityScore(input: ConversationPriorityInput): number {
  const info = conversationPriorityInfo(input.partKey);
  const kindOffset = input.kind === "vocab" ? 60_000 : input.kind === "dialogue" ? 30_000 : 0;
  // One authored step outweighs a 1,500-point commonality gap — the same
  // relative strength it had before commonality was scaled up, so an editor's
  // deliberate promotion or demotion still decides the order inside a pack.
  const authored = Number.isFinite(input.lessonPriority)
    ? Math.max(-2, Math.min(2, Number(input.lessonPriority))) * 1_500_000
    : 0;
  const commonality = Number.isFinite(input.commonality)
    ? Math.max(0, Math.min(5_000, Number(input.commonality)))
    : 5_000;

  // Within-band total stays below the 10,000,000 band gap:
  // 5,000,000 + 3,000,000 + 60,000 + packRank < 10,000,000.
  const base = info.band * 10_000_000
    + commonality * 1_000
    + authored
    + kindOffset
    + info.packRank;

  // Bigger than the highest band (5) can ever reach on its own — a
  // deprioritized item still sorts by all of the above AMONG other
  // deprioritized items, it is just never ahead of an ordinary one.
  return input.deprioritized ? base + 100_000_000 : base;
}

/**
 * The packs a Fast track sitting is allowed to draw from.
 *
 * Continue learning walks the whole curriculum in order, which is right for
 * somebody working through a course and wrong for somebody who wants to hold
 * a conversation this month. The course teaches the rooms of a house, the
 * things on a desk, the parts of a car — all of it worth knowing, none of it
 * what you reach for first when you are talking to a person.
 *
 * So this is the two conversational bands and nothing else, in the order they
 * were already authored in: opening a conversation, repairing it, reacting,
 * making plans, and then the topics a normal exchange actually turns to —
 * family, food, money, health, directions, the weather. What it leaves out is
 * as deliberate as what it keeps: no rooms, no furniture, no stationery.
 *
 * Written as the two existing lists joined rather than a third list copied
 * out of them, so a pack promoted into the essentials tomorrow is in the fast
 * track tomorrow and nobody has to remember this file exists.
 */
export const FAST_TRACK_PACKS: readonly string[] = [
  ...CONVERSATION_ESSENTIAL_PACKS,
  ...EVERYDAY_CONVERSATION_PACKS,
];

/**
 * Where a Fast track sitting picks up.
 *
 * The first conversational pack that still has something to teach, in the
 * authored order — so it continues rather than restarting, the same promise
 * Continue learning makes, over a much smaller course.
 *
 * `hasFresh` is passed in rather than computed here because deciding whether
 * a pack has fresh content means building its session, which needs the review
 * state, the learner and half the lesson engine. This file knows which packs
 * are conversational; it should not also have to know how a sitting is built.
 *
 * When every conversational pack is finished it returns the first one that
 * exists instead of null: the button is on screen and pressing it has to
 * teach something. Reviews inside that pack are what a finished course has
 * left to offer, and that is the same answer Continue learning gives.
 */
export function nextFastTrackPart(
  available: Record<string, unknown>,
  hasFresh: (packId: string) => boolean
): string | null {
  const present = FAST_TRACK_PACKS.filter((packId) => Boolean(available[packId]));
  return present.find((packId) => hasFresh(packId)) ?? present[0] ?? null;
}
